name: Build Project
on: [push]
jobs:
  build-project:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive
      - name: Setup
        run: mkdir cmake-build-release
      - name: Generate CMake Project
        run: cmake .. -DCMAKE_BUILD_RELEASE
        working-directory: cmake-build-release
      - name: Build Project
        run: cmake --build build --target digisim
      - name: Build Tests
        run: cmake --build build --target digisim-tests
      - name: Test Project
        run: ./build/tests/digisim-tests
